use_frameworks!

platform :ios, '10.0'

target 'HFAdmobManager_Example' do
  pod 'HFAdmobManager', :path => '../'

  target 'HFAdmobManager_Tests' do
    inherit! :search_paths
    
    
  end
  
  
  pod 'AFNetworking', '~> 3.0', :subspecs => ['Reachability', 'Serialization', 'Security', 'NSURLSession']
  pod 'GZIP', '~> 1.2'
  pod "MJExtension"
  
  
end
